In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
import os
os.getcwd()

'C:\\Users\\KOLLIPARA DHYANESH\\Desktop\\remote internship 2020\\Black Friday Dataset'

In [4]:
os.chdir("C:/Users/KOLLIPARA DHYANESH/Desktop/remote internship 2020/Black Friday Dataset")
os.getcwd()

'C:\\Users\\KOLLIPARA DHYANESH\\Desktop\\remote internship 2020\\Black Friday Dataset'

In [95]:
data1=pd.read_csv("consumer.csv")
data1

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
5       1000003  P00193542      M  26-35          15             A   
6       1000004  P00184942      M  46-50           7             B   
7       1000004  P00346142      M  46-50           7             B   
8       1000004   P0097242      M  46-50           7             B   
9       1000005  P00274942      M  26-35          20             A   
10      1000005  P00251242      M  26-35          20             A   
11      1000005  P00014542      M  26-35          20             A   
12      1000005  P00031342      M  26-35          20             A   
13      1000005  P00145042      M  26-35          20             A   
14      1000006  P00231342      F  51-55           9             A   
15      1000006  P00190242      F  51-55           9             A   
16      1000006   P0096642      F  51-55           9             A   
17      1000006  P00058442      F  51-55           9             A   
18      1000007  P00036842      M  36-45           1             B   
19      1000008  P00249542      M  26-35          12             C   
20      1000008  P00220442      M  26-35          12             C   
21      1000008  P00156442      M  26-35          12             C   
22      1000008  P00213742      M  26-35          12             C   
23      1000008  P00214442      M  26-35          12             C   
24      1000008  P00303442      M  26-35          12             C   
25      1000009  P00135742      M  26-35          17             C   
26      1000009  P00039942      M  26-35          17             C   
27      1000009  P00161442      M  26-35          17             C   
28      1000009  P00078742      M  26-35          17             C   
29      1000010  P00085942      F  36-45           1             B   
...         ...        ...    ...    ...         ...           ...   
550038  1005995  P00375436      F  36-45           1             C   
550039  1005996  P00371644      F  26-35           0             B   
550040  1005997  P00370853      F  26-35           7             A   
550041  1006000  P00371644      M  46-50          17             B   
550042  1006002  P00371644      M  51-55           0             C   
550043  1006003  P00370293      F  46-50          17             C   
550044  1006004  P00370853      F  26-35          15             C   
550045  1006005  P00371644      F  26-35           5             C   
550046  1006006  P00375436      F   0-17           0             C   
550047  1006009  P00372445      F  26-35          12             C   
550048  1006010  P00371644      M  36-45           0             C   
550049  1006011  P00375436      M  36-45          15             C   
550050  1006012  P00371644      M  36-45          15             C   
550051  1006013  P00375436      F  26-35          20             C   
550052  1006016  P00375436      M  46-50           1             B   
550053  1006017  P00371644      F  36-45           7             B   
550054  1006018  P00370293      M  36-45           1             C   
550055  1006019  P00372445      M  26-35           0             A   
550056  1006022  P00375436      M  26-35          17             C   
550057  1006023  P00370853      M  26-35           0             C   
550058  1006024  P00372445      M  26-35          12             A   
550059  1006025  P00370853      F  26-35           1             B   
550060  1006026  P00371644      M  36-45           6             C   
550061  1006029  P00372445      F  26-35           1             C   
550062  1006032  P00372445      M  46-50           7             A   
550063  1006033  P

In [96]:
import chart_studio.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode

In [97]:
import cufflinks
cufflinks.go_offline(connected=True)
init_notebook_mode(connected=True)

# Missing values

The fillna() function is used to fill NA/NaN values using the specified method. Value to use to fill holes (e.g. 0), alternately a dict/Series/DataFrame of values specifying which value to use for each index (for a Series) or column

In [98]:
data1.isnull().any()

User_ID                       False
Product_ID                    False
Gender                        False
Age                           False
Occupation                    False
City_Category                 False
Stay_In_Current_City_Years    False
Marital_Status                False
Product_Category_1            False
Product_Category_2             True
Product_Category_3             True
Purchase                      False
dtype: bool

In [106]:
data1['Product_Category_3'].fillna(data1['Product_Category_3'].mean(),inplace=True)

In [107]:
data1['Product_Category_2'].fillna(data1['Product_Category_2'].mean(),inplace=True)

In [108]:
data1.isnull().any()

User_ID                       False
Product_ID                    False
Gender                        False
Age                           False
Occupation                    False
City_Category                 False
Stay_In_Current_City_Years    False
Marital_Status                False
Product_Category_1            False
Product_Category_2            False
Product_Category_3            False
Purchase                      False
dtype: bool

In [109]:
data1

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
5       1000003  P00193542      M  26-35          15             A   
6       1000004  P00184942      M  46-50           7             B   
7       1000004  P00346142      M  46-50           7             B   
8       1000004   P0097242      M  46-50           7             B   
9       1000005  P00274942      M  26-35          20             A   
10      1000005  P00251242      M  26-35          20             A   
11      1000005  P00014542      M  26-35          20             A   
12      1000005  P00031342      M  26-35          20             A   
13      1000005  P00145042      M  26-35          20             A   
14      1000006  P00231342      F  51-55           9             A   
15      1000006  P00190242      F  51-55           9             A   
16      1000006   P0096642      F  51-55           9             A   
17      1000006  P00058442      F  51-55           9             A   
18      1000007  P00036842      M  36-45           1             B   
19      1000008  P00249542      M  26-35          12             C   
20      1000008  P00220442      M  26-35          12             C   
21      1000008  P00156442      M  26-35          12             C   
22      1000008  P00213742      M  26-35          12             C   
23      1000008  P00214442      M  26-35          12             C   
24      1000008  P00303442      M  26-35          12             C   
25      1000009  P00135742      M  26-35          17             C   
26      1000009  P00039942      M  26-35          17             C   
27      1000009  P00161442      M  26-35          17             C   
28      1000009  P00078742      M  26-35          17             C   
29      1000010  P00085942      F  36-45           1             B   
...         ...        ...    ...    ...         ...           ...   
550038  1005995  P00375436      F  36-45           1             C   
550039  1005996  P00371644      F  26-35           0             B   
550040  1005997  P00370853      F  26-35           7             A   
550041  1006000  P00371644      M  46-50          17             B   
550042  1006002  P00371644      M  51-55           0             C   
550043  1006003  P00370293      F  46-50          17             C   
550044  1006004  P00370853      F  26-35          15             C   
550045  1006005  P00371644      F  26-35           5             C   
550046  1006006  P00375436      F   0-17           0             C   
550047  1006009  P00372445      F  26-35          12             C   
550048  1006010  P00371644      M  36-45           0             C   
550049  1006011  P00375436      M  36-45          15             C   
550050  1006012  P00371644      M  36-45          15             C   
550051  1006013  P00375436      F  26-35          20             C   
550052  1006016  P00375436      M  46-50           1             B   
550053  1006017  P00371644      F  36-45           7             B   
550054  1006018  P00370293      M  36-45           1             C   
550055  1006019  P00372445      M  26-35           0             A   
550056  1006022  P00375436      M  26-35          17             C   
550057  1006023  P00370853      M  26-35           0             C   
550058  1006024  P00372445      M  26-35          12             A   
550059  1006025  P00370853      F  26-35           1             B   
550060  1006026  P00371644      M  36-45           6             C   
550061  1006029  P00372445      F  26-35           1             C   
550062  1006032  P00372445      M  46-50           7             A   
550063  1006033  P

#  Splitting Dataset in to Independent variable and Dependent variable

In [126]:
x=data1.iloc[:,2:11].values
x

array([[0, 0, 10, ..., 3, 9.842329251122386, 12.668243206790512],
       [0, 0, 10, ..., 1, 6.0, 14.0],
       [0, 0, 10, ..., 12, 9.842329251122386, 12.668243206790512],
       ...,
       [0, 2, 15, ..., 20, 9.842329251122386, 12.668243206790512],
       [0, 6, 1, ..., 20, 9.842329251122386, 12.668243206790512],
       [0, 4, 0, ..., 20, 9.842329251122386, 12.668243206790512]],
      dtype=object)

In [127]:
y=data1.iloc[:,11].values
y

array([ 8370, 15200,  1422, ...,   137,   365,   490], dtype=int64)

# Label Encoding

Another approach to encoding categorical values is to use a technique called label encoding. Label encoding is simply converting each value in a column to a number

In [128]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
data1['Gender']=labelencoder_y.fit_transform(data1['Gender'])
data1['City_Category']=labelencoder_y.fit_transform(data1['City_Category'])
data1['Product_ID']=labelencoder_y.fit_transform(data1['Product_ID'])

In [129]:
data1

User_ID  Product_ID  Gender  Age  Occupation  City_Category  \
0             0         672       0    0          10              0   
1             0        2376       0    0          10              0   
2             0         852       0    0          10              0   
3             0         828       0    0          10              0   
4             1        2734       1    6          16              2   
5             2        1831       1    2          15              0   
6             3        1745       1    4           7              1   
7             3        3320       1    4           7              1   
8             3        3604       1    4           7              1   
9             4        2631       1    2          20              0   
10            4        2398       1    2          20              0   
11            4         140       1    2          20              0   
12            4         307       1    2          20              0   
13            4        1355       1    2          20              0   
14            5        2203       0    5           9              0   
15            5        1798       0    5           9              0   
16            5        3598       0    5           9              0   
17            5         573       0    5           9              0   
18            6         362       1    3           1              1   
19            7        2382       1    2          12              2   
20            7        2096       1    2          12              2   
21            7        1469       1    2          12              2   
22            7        2029       1    2          12              2   
23            7        2036       1    2          12              2   
24            7        2909       1    2          12              2   
25            8        1264       1    2          17              2   
26            8         391       1    2          17              2   
27            8        1517       1    2          17              2   
28            8         765       1    2          17              2   
29            9         833       0    3           1              1   
...         ...         ...     ...  ...         ...            ...   
550038     5845        3568       0    3           1              2   
550039     5846        3566       0    2           0              1   
550040     5847        3565       0    2           7              0   
550041     5850        3566       1    4          17              1   
550042     5852        3566       1    5           0              2   
550043     5853        3560       0    4          17              2   
550044     5854        3565       0    2          15              2   
550045     5855        3566       0    2           5              2   
550046     5856        3568       0    0           0              2   
550047     5859        3567       0    2          12              2   
550048     5860        3566       1    3           0              2   
550049     5861        3568       1    3          15              2   
550050     5862        3566       1    3          15              2   
550051     5863        3568       0    2          20              2   
550052     5866        3568       1    4           1              1   
550053     5867        3566       0    3           7              1   
550054     5868        3560       1    3           1              2   
550055     5869        3567       1    2           0              0   
550056     5872        3568       1    2          17              2   
550057     5873        3565       1    2           0              2   
550058     5874        3567       1    2          12              0   
550059     5875        3565       0    2           1              1   
550060     5876        3566       1    3           6              2   
550061     5879        3567       0    2           1              2   
550062     5882        3567     

In [130]:
data=data1['Gender'].value_counts()
data

1    414259
0    135809
Name: Gender, dtype: int64

In [131]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [132]:
x[:,2]=lb.fit_transform(x[:,2])
x

array([[0, 0, 10, ..., 3, 9.842329251122386, 12.668243206790512],
       [0, 0, 10, ..., 1, 6.0, 14.0],
       [0, 0, 10, ..., 12, 9.842329251122386, 12.668243206790512],
       ...,
       [0, 2, 15, ..., 20, 9.842329251122386, 12.668243206790512],
       [0, 6, 1, ..., 20, 9.842329251122386, 12.668243206790512],
       [0, 4, 0, ..., 20, 9.842329251122386, 12.668243206790512]],
      dtype=object)

In [133]:
from sklearn.preprocessing import LabelEncoder
lb1=LabelEncoder()

In [134]:
x[:,5]

array([0, 0, 0, ..., 1, 0, 1], dtype=object)

In [135]:
x[:,5]=lb.fit_transform(x[:,5])
x

array([[0, 0, 10, ..., 3, 9.842329251122386, 12.668243206790512],
       [0, 0, 10, ..., 1, 6.0, 14.0],
       [0, 0, 10, ..., 12, 9.842329251122386, 12.668243206790512],
       ...,
       [0, 2, 15, ..., 20, 9.842329251122386, 12.668243206790512],
       [0, 6, 1, ..., 20, 9.842329251122386, 12.668243206790512],
       [0, 4, 0, ..., 20, 9.842329251122386, 12.668243206790512]],
      dtype=object)

In [136]:
data1

User_ID  Product_ID  Gender  Age  Occupation  City_Category  \
0             0         672       0    0          10              0   
1             0        2376       0    0          10              0   
2             0         852       0    0          10              0   
3             0         828       0    0          10              0   
4             1        2734       1    6          16              2   
5             2        1831       1    2          15              0   
6             3        1745       1    4           7              1   
7             3        3320       1    4           7              1   
8             3        3604       1    4           7              1   
9             4        2631       1    2          20              0   
10            4        2398       1    2          20              0   
11            4         140       1    2          20              0   
12            4         307       1    2          20              0   
13            4        1355       1    2          20              0   
14            5        2203       0    5           9              0   
15            5        1798       0    5           9              0   
16            5        3598       0    5           9              0   
17            5         573       0    5           9              0   
18            6         362       1    3           1              1   
19            7        2382       1    2          12              2   
20            7        2096       1    2          12              2   
21            7        1469       1    2          12              2   
22            7        2029       1    2          12              2   
23            7        2036       1    2          12              2   
24            7        2909       1    2          12              2   
25            8        1264       1    2          17              2   
26            8         391       1    2          17              2   
27            8        1517       1    2          17              2   
28            8         765       1    2          17              2   
29            9         833       0    3           1              1   
...         ...         ...     ...  ...         ...            ...   
550038     5845        3568       0    3           1              2   
550039     5846        3566       0    2           0              1   
550040     5847        3565       0    2           7              0   
550041     5850        3566       1    4          17              1   
550042     5852        3566       1    5           0              2   
550043     5853        3560       0    4          17              2   
550044     5854        3565       0    2          15              2   
550045     5855        3566       0    2           5              2   
550046     5856        3568       0    0           0              2   
550047     5859        3567       0    2          12              2   
550048     5860        3566       1    3           0              2   
550049     5861        3568       1    3          15              2   
550050     5862        3566       1    3          15              2   
550051     5863        3568       0    2          20              2   
550052     5866        3568       1    4           1              1   
550053     5867        3566       0    3           7              1   
550054     5868        3560       1    3           1              2   
550055     5869        3567       1    2           0              0   
550056     5872        3568       1    2          17              2   
550057     5873        3565       1    2           0              2   
550058     5874        3567       1    2          12              0   
550059     5875        3565       0    2           1              1   
550060     5876        3566       1    3           6              2   
550061     5879        3567       0    2           1              2   
550062     5882        3567     

# OneHot Encoding

It refers to splitting the column which contains numerical categorical data to many columns depending on the number of categories present in that column. Each column contains “0” or “1” corresponding to which column it has been placed.

In [137]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer([("on",OneHotEncoder(),[1])],remainder="passthrough")
x=ct.fit_transform(x)
x

C:\Users\KOLLIPARA DHYANESH\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning:

The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.



array([[1.0, 0.0, 0.0, ..., 3, 9.842329251122386, 12.668243206790512],
       [1.0, 0.0, 0.0, ..., 1, 6.0, 14.0],
       [1.0, 0.0, 0.0, ..., 12, 9.842329251122386, 12.668243206790512],
       ...,
       [0.0, 0.0, 1.0, ..., 20, 9.842329251122386, 12.668243206790512],
       [0.0, 0.0, 0.0, ..., 20, 9.842329251122386, 12.668243206790512],
       [0.0, 0.0, 0.0, ..., 20, 9.842329251122386, 12.668243206790512]],
      dtype=object)